spring.application.name=keycloak-adapter
server.port=8085

# Keycloak — configurar cuando se levante el servidor Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/sanos-y-salvos

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
